### ISSUE TITLE
What is the purpose of this repo?

### ISSUE THREAD

**Issue by didlie** [krixano/ZeroExchange#1]
What are your goals with this project?

**Comment by krixano** [comment]
Nonetheless, I will make a quick readme that tells what this repo is for.

**Comment by didlie** [comment]
Do you fully understand the ZeroNet code? Can you work with me to dissect it?

**Comment by krixano** [comment]
I don't understand the internals of ZeroNet, but I understand the overarching concepts of what it does and how it does what it does.
